[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_OMIT_KEYS = "VITE_BASIQ_API_KEY"

[[plugins]]
package = "@netlify/plugin-functions-install-core"

# Redirecionar chamadas de API para as funções Netlify
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirecionar todas as outras rotas para o SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
