[build]
  command = "pnpm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_OMIT_KEYS = "VITE_BASIQ_API_KEY"
  VITE_APP_ENV = "production"
  NPM_FLAGS = "--version" # Evita que o Netlify execute npm install
  PNPM_VERSION = "10.10.0" # Especifica a versão do pnpm a ser usada
  PNPM_FLAGS = "--no-frozen-lockfile" # Permite que o pnpm atualize o lockfile durante a instalação

# Garantir que as funções Netlify tenham acesso à variável VITE_BASIQ_API_KEY
[functions]
  node_bundler = "esbuild"
  included_files = []
  external_node_modules = []

[[plugins]]
package = "@netlify/plugin-functions-install-core"

# Redirecionar chamadas de API para as funções Netlify
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirecionar todas as outras rotas para o SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
